### ISSUE TITLE
Better syntax for `accept`

### ISSUE THREAD

**Issue by jeremyrsmith** [jeremyrsmith/featherbed#4]
Currently `accept` requires the use of a Shapeless Coproduct type syntax:

```scala
client.get("foo").accept[Coproduct.`"application/json","text/xml"`.T]
```

This is less than ideal.  Probably, a better syntax could be achieved by accepting a product of singleton types and converting that to an inferred Coproduct at compile time, which would look more like: 

```scala
client.get("foo").accept("application/json", "text/xml")
```

If that's not possible, some common types could be assigned type aliases like this (or something):

```scala
val jsonWitness = Witness("application/json")
type JSON = jsonWitness.T

val textXmlWitness = Witness("text/xml")
type `text/xml` = textXmlWitness.T
```

And then they could be combined using Coproduct combinator:

```scala
client.get("foo").accept[JSON :+: `text/xml` :+: CNil]
```

which would be slightly less objectionable.  Would that be a good idea?

**Comment by Matthijn** [comment]
First of, great library, it really seems to make handling REST services a blast. There's one thing I think that has the possibility for improvement, and that is not having to describe the accept on every endpoint. I'm not sure I understand why that is needed. The string syntax does beat the syntax mentioned up above (my scala skills are not quite there to understand why this way was chosen).

Would it not be better to be able to define the accept on the client itself? Since most REST services (and I feel for you if this is not the case with your particular one) always return the same content type anyway. See screenshot for what I mean.

<img width="1131" alt="screen shot 2017-12-12 at 22 15 34" src="https://user-images.githubusercontent.com/1755544/33909095-c13a3292-df8a-11e7-8c1d-4749bd02cda2.png">

Even if this will not be possible, you for sure have a user of featherbed, cause the other things, I really like!
